/**
 * Static Team Roster Configuration
 * 
 * Update team member details directly here without needing any backend or database upload.
 * Public tiers:
 *  - chiefBoard: President, Vice President, Managing Director (top spotlight tier)
 *  - boardMembers: Leads and core domain directors
 *  - teamMembers: Core developers, designers, and coordinators
 */

export const chiefBoard = [
  {
    name: "P Krishna Neeraj",
    role: "Lead",
    linkedin_url: "https://www.linkedin.com/in/krishna-neeraj-596051277/",
    github_url: "",
    twitter_url: "",
    instagram_url: "",
    email: "krishna_pattapu@srmap.edu.in",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Rishi Samani",
    role: "Associate Lead",
    linkedin_url: "https://www.linkedin.com/in/rishi-samani-0bb224397/",
    github_url: "",
    twitter_url: "",
    instagram_url: "",
    email: "rishi_samani@srmap.edu.in",
    portfolio_url: "",
    image_url: "https://nakwfnivpodkvperbfkf.supabase.co/storage/v1/object/public/Teams/Rishi.jpg",
  },
  {
    name: "Hema Devi",
    role: "Co Lead",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    twitter_url: "",
    instagram_url: "",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
  {
    role: "General Secretary",
    name: "K Akhil",
    linkedin_url: "https://www.linkedin.com/in/akhil-koppuravuri-390363324/",
    github_url: "",
    twitter_url: "",
    instagram_url: "",
    email: "akhil_koppuravuri@srmap.edu.in",
    portfolio_url: "",
    image_url: "https://nakwfnivpodkvperbfkf.supabase.co/storage/v1/object/public/Teams/AKHIL.jpeg",
  },
  {
    role: "General Secretary",
    name: "A Jahnavi",
    linkedin_url: "https://www.linkedin.com/in/jahnavi-alaham/",
    github_url: "",
    twitter_url: "",
    instagram_url: "",
    email: "jahnavi_a@srmap.edu.in",
    portfolio_url: "",
    image_url: "",
  },
];

export const boardMembers = [
  {
    name: "Y Naga Pragnesh",
    role: "Technical Head",
    linkedin_url: "https://linkedin.com/in/yedrunagapragnesh",
    github_url: "https://github.com/Pragnesh-10",
    twitter_url: "https://x.com/pragnesh5790",
    instagram_url: "",
    email: "pragnesh_yedru@srmap.edu.in",
    portfolio_url: "https://ynpragnesh.pages.dev/",
    image_url: "https://nakwfnivpodkvperbfkf.supabase.co/storage/v1/object/public/Teams/Pragnesh.jpeg",
  },
    {
    name: "Yuvraj Singh",
    role: "Technical Co Head",
    linkedin_url: "https://www.linkedin.com/in/yuvraj-singh-3178saturn/",
    github_url: "https://github.com/YUVRAJ-SINGH-3178",
    twitter_url: "",
    instagram_url: "",
    email: "yuvraj_singh@srmap.edu.in",
    portfolio_url: "yuvrajsingh07.vercel.app",
    image_url: "https://nakwfnivpodkvperbfkf.supabase.co/storage/v1/object/public/Teams/YuvrajSingh_Technical%20Co-Lead.png",
  },
  {
    name: "Design Lead Name",
    role: "Design & UI/UX Lead",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "https://github.com/",
    twitter_url: "",
    instagram_url: "https://instagram.com/",
    email: "design@srmap.edu.in",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Operations Lead Name",
    role: "Operations Lead",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    twitter_url: "",
    instagram_url: "https://instagram.com/",
    email: "ops@srmap.edu.in",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Events Lead Name",
    role: "Events Lead",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    twitter_url: "https://x.com/",
    instagram_url: "https://instagram.com/",
    email: "events@srmap.edu.in",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "PR & Marketing Lead",
    role: "PR & Media Lead",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    twitter_url: "",
    instagram_url: "https://instagram.com/",
    email: "pr@srmap.edu.in",
    portfolio_url: "",
    image_url: "",
  },
];

export const teamMembers = [
  {
    name: "Frontend Developer",
    role: "Core Web Developer",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "https://github.com/",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Backend Specialist",
    role: "Core Cloud / DevOps",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "https://github.com/",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "AI & ML Researcher",
    role: "Core AI Member",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "https://github.com/",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Creative Strategist",
    role: "Core Design Member",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Event Coordinator",
    role: "Core Logistics Member",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
  {
    name: "Community Outreach",
    role: "Core PR Member",
    linkedin_url: "https://linkedin.com/in/",
    github_url: "",
    email: "",
    portfolio_url: "",
    image_url: "",
  },
];
